image_width: 648
image_height: 516
camera_name: 15360545
camera_matrix:
  rows: 3
  cols: 3
  data: [372.4983247055472, 0, 327.554966020216, 0, 372.7355129587445, 255.1680646833106, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.3044282590143014, 0.06954950579326441, -8.155056188318412e-05, -0.000110065579593621, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.9986450024468553, 0.05116563961639497, 0.00949928473968454, -0.05147624006689343, 0.9980255226197071, 0.03598962222969274, -0.007639096575902407, -0.03642984384135668, 0.9993070152266512]
projection_matrix:
  rows: 3
  cols: 4
  data: [327.6064855571187, 0, 311.3664646148682, -53.12239065198445, 0, 327.6064855571187, 254.9724140167236, 0, 0, 0, 1, 0]