local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 15.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  inflation_radius: 0.3
  footprint_padding: -0.1
  cost_scaling_factor: 1.0
