global_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

