DWAPlannerROS:

  #####################

  # The x acceleration limit of the robot in meters/sec^2
  # default: 2.5
  acc_lim_x: 10.0

  #The maximum x velocity for the robot in m/s.
  #default: 0.55
  max_vel_x: 1.4

  #The minimum x velocity for the robot in m/s, negative for backwards motion.
  #default: 0.0
  min_vel_x: -0.1

  #####################

  # The y acceleration limit of the robot in meters/sec^2
  # default: 2.5
  acc_lim_y: 10.0

  # The maximum y velocity for the robot in m/s
  # default: 0.1
  max_vel_y: 0.0

  # The minimum y velocity for the robot in m/s
  # default: -0.1
  min_vel_y: 0.0

  #####################

  # The rotational acceleration limit of the robot in radians/sec^2
  # default: 3.2
  acc_lim_th: 10.0

  # The absolute value of the maximum rotational velocity for the robot in rad/s
  # default: 1.0
  max_rot_vel: 1.0

  # The absolute value of the minimum rotational velocity for the robot in rad/s
  # default: 0.4
  min_rot_vel: 0.4

  #####################

  # The absolute value of the maximum translational velocity for the robot in m/s
  # default: 0.55
  max_trans_vel: 1.2

  # The absolute value of the minimum translational velocity for the robot in m/s
  # default: 0.1
  min_trans_vel: 0.5

  #####################

  max_scaling_factor: 0.2

  # default 32.0
  path_distance_bias: 0.01

  goal_distance_bias: 22.0

  # default 0.01
  # The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale: 20.0

  # default true
  # Defines whether or not to eat up the plan as the robot moves along the path. If set to true, points will fall off
  #     the end of the plan once the robot moves 1 meter past them.
  prune_plan: true

  # default: 3
  # The number of samples to use when exploring the x velocity space
  vx_samples: 2

  # default: 10
  # The number of samples to use when exploring the y velocity space
  vy_samples: 5

  # default 1.7
  # The amount of time to forward-simulate trajectories in seconds
  sim_time: 1.0

  # default 0.025
  # The step size, in meters, to take between points on a given trajectory
  sim_granularity: 0.01

  angular_sim_granularity: 0.1

  yaw_goal_tolerance: 3.1416
  xy_goal_tolerance: 0.5
