scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 2
    window: 1
- name: dark_shadows
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 50
    upper_threshold: 5000
    disp_histogram: 0
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.22
    upper_threshold: 150.0